[build-system]
requires = [
  "setuptools",
  "setuptools_scm >= 2.0.0, <3",
]
build-backend = "setuptools.build_meta"

[project]
name = "juju-lnav"
version = "1.0.0"
dependencies = [
  "requests",
  'importlib-metadata; python_version<"3.8"',
]

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters
