name: juju-lnav
base: core24
adopt-info: juju-lnav
summary: A script to look at logs from multiple Juju units
description: |
  The `juju-lnav` command displays multiple log files from multiple machines in one view. It uses the `lnav` log file viewer, [lnav.org](lnav.org), which needs to be installed separately. For example,

  For example, after installing `lnav`,

  ```console
  sudo snap install lnav
  ```

  running

  ```console
  juju-lnav octavia:/var/log/octavia/*.log{,1}
  ```

  will open the current and the first rotated log files from all of the `octavia` units.

  Likewise

  ```console
  juju-lnav octavia:/var/log/octavia/*.log \
    nova-cloud-controller:/var/log/nova
  ```

  Will load the logs on all `octavia` ending in `.log` and all files on `nova-cloud-controller` units.

grade: stable
confinement: strict

plugs:
  lnav-executable:
    interface: content
    target: $SNAP/lnav-snap
    default-provider: lnav

apps:
  juju-lnav:
    command: usr/bin/juju-lnav

parts:
  juju-lnav:
    plugin: dump
    source: .
    build-packages:
      - git
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --always)
    organize:
      juju-lnav: usr/bin/juju-lnav
    stage:
      - usr/bin/juju-lnav
