name: juju-lnav
base: core24
adopt-info: juju-lnav
summary: A script to look at logs from multiple Juju units
description: |
  The `juju-lnav` command is a helper script to call `lnav` (needs to be
  installed via package or snap) on multiple machines, applications, or units.

  For example, after installing `lnav`,

  ```
  sudo snap install lnav
  ```

  The log files of units in a Juju model can be inspected with
          
  ```
  juju-lnav octavia:/var/log/octavia/*.log{,1}
  ```

  which will open the current and the first rotated log files from all of the
  `octavia` units.

  Likewise

  ```
  juju-lnav octavia:/var/log/octavia/*.log \
      nova-cloud-controller:/var/log/nova/*.log
  ```

  Will load the logs on all `octavia` and all `nova-cloud-controller` units.

  For more information on how to use `lnav` please visit lnav.org.

grade: stable
confinement: strict

plugs:
  lnav-executable:
    interface: content
    target: $SNAP/lnav-snap
    default-provider: lnav

apps:
  juju-lnav:
    command: usr/bin/juju-lnav

parts:
  juju-lnav:
    plugin: dump
    source: .
    build-packages:
      - git
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --always)
    organize:
      juju-lnav: usr/bin/juju-lnav
    stage:
      - usr/bin/juju-lnav
