name: juju-lnav
base: core20
adopt-info: juju-lnav
summary: A script to look at logs from multiple Juju units
description: |
  The `juju-lnav` command is a helper script to call `lnav` (needs to be
  installed via package or snap) on multiple machines, applications, or units.
  For example,
          
  ```
  $ ./tools/juju-lnav octavia:/var/log/octavia/*.log{,1}
  ```

  Will open the current and the first rotated log files from all of the
  `octavia` units.

  Likewise

  ```
  $ ./tools/juju-lnav octavia:/var/log/octavia/*.log \
      nova-cloud-controller:/var/log/nova/*.log
  ```

  Will load the logs on all `octavia` and all `nova-cloud-controller` units.

  For more information on how to use `lnav` please visit lnav.org.

grade: devel
confinement: devmode

apps:
  juju-lnav:
    command: usr/bin/juju-lnav

parts:
  selective-checkout:
    source: https://github.com/Lin-Buo-Ren/selective-checkout.git
    source-tag: v2.0.2
    plugin: dump
    build-packages:
    - git
    - curl
    - jq
    - sed
    stage:
      - scriptlets/selective-checkout
    prime:
      - -*

  juju-lnav:
    after:
      - selective-checkout
    plugin: dump
    source: .
    override-pull: |
      snapcraftctl pull

      pwd
      ls -lh

      "$SNAPCRAFT_STAGE"/scriptlets/selective-checkout --debug \
        --force-snapshot
    organize:
      juju-lnav: usr/bin/juju-lnav
    stage:
      - usr/bin/juju-lnav
