name: Build and Upload Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-snap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft
      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

  build-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends --yes pip
          pip install poetry==1.8.2
          poetry install
      - name: Build Python package
        run: poetry build
